# Generated by Django 3.0.2 on 2020-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('useremail', models.EmailField(max_length=254)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('Iam', models.CharField(choices=[('Owner', 'Owner'), ('Dealer', 'Dealer')], default='Owner', max_length=10)),
                ('ptype', models.CharField(choices=[('Bunglow', 'Bunglow'), ('Flat', 'Flat')], default='Flat', max_length=10)),
                ('pfor', models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=5)),
                ('Buildname', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=200)),
                ('Area', models.CharField(choices=[('Bopal', 'Bopal'), ('Thaltej', 'Thaltej')], default='Bopal', max_length=9)),
                ('bhk', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Other', 'Other')], default='Other', max_length=7)),
                ('Superbuildup', models.IntegerField()),
                ('buildup', models.IntegerField()),
                ('meter', models.CharField(choices=[('Vaar', 'Vaar'), ('sq_ft', 'sq_ft')], default='sq_ft', max_length=5)),
                ('addmore', models.TextField(max_length=1000)),
                ('furnished', models.CharField(choices=[('Non-Furnished', 'Non-Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Fully-Furnished', 'Fully-Furnished')], default='Non-Furnished', max_length=20)),
                ('pfloor', models.IntegerField()),
                ('tfloor', models.IntegerField()),
                ('cparkinng', models.BooleanField()),
                ('oparkinng', models.BooleanField()),
                ('age', models.CharField(choices=[('less than 1 year', 'less than 1 year'), ('Between 1-5 years', 'Between 1-5 years'), ('Between 6-10 years', 'Between 6-10 years'), ('More than 10 years', 'More than 10 years')], default='Between 6-10 years', max_length=19)),
                ('price', models.CharField(max_length=100)),
                ('nego', models.BooleanField()),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
                ('image3', models.ImageField(upload_to='uploads/')),
                ('image4', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'propertys',
            },
        ),
    ]
