# Generated by Django 3.0.2 on 2020-10-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Iam',
            new_name='Youare',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='mobile',
            new_name='cmobile',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='cparkinng',
            new_name='cparking',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='oparkinng',
            new_name='oparking',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pfor',
            new_name='propertyfor',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ptype',
            new_name='propertytype',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Superbuildup',
            new_name='superbuildup',
        ),
    ]
